# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: bedobi.com
title: Bedobi
email: fre.and.fri@gmail.com
description: Design, Develop, Use. Award winning apps in portfolio.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    url: mailto:fre.and.fri@gmail.com
    icon: envelope
  - title: github
    url: https://github.com/androidfred
    icon: github
  - title: resume
    url: https://docs.google.com/document/d/1DaAX7Vtol9FLeXiUEBpGxO7mkfMzVZb5zYwdzVMBb2o
    icon: file-text-o
